### ISSUE TITLE
Support Keyed services

### ISSUE THREAD

**Issue by ElanHasson** [JasperFx/oakton#86]
Using .NET 8 and registered keyed services. Also using Lamar, Wolverine, Marten.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=This service descriptor is keyed. Your service provider may not support keyed services.
  Source=Microsoft.Extensions.DependencyInjection.Abstractions
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.ThrowKeyedDescriptor()
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.get_ImplementationType()
   at Oakton.Resources.ResourceHostExtensions.<>c.<AddResourceSetupOnStartup>b__0_0(ServiceDescriptor x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Oakton.Resources.ResourceHostExtensions.AddResourceSetupOnStartup(IServiceCollection services, StartupAction action)
   at Program.<<Main>$>d__0.MoveNext() 
```

**Comment by ElanHasson** [comment]
I now know this was  https://github.com/dotnet/runtime/issues/95789

I see the change made to marten to handle this. Will see if this still happens here and if it does, i'll send a PR to fix.
